permalink: /:year/:month/:day/:title:output_ext
url: https://polyamory.ie
name: Polyamory.ie
description: The Most Officialest Polyamory Blog in Ireland
collections:
  community:
  resources:
  events:
  mental:
  physical:
  friends:
  glossary:
plugins:
  - jekyll-diagrams
jekyll-diagrams:
  graphviz:
    default_layout: neato
    graph_attributes:
      bgcolor: transparent
    node_attributes:
      fillcolor: transparent
      fontcolor: "#DDDDDD"
      color: "#DDDDDD"
      style: filled
    edge_attributes:
      color: "#DDDDDD"
      dir: none
