server {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri.html $uri $uri/ =404;
    error_page 404 /404.html;

    location = /health {
        access_log off;
    }
}
