name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Test
      run: echo ok
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: shish2k/polyamory.ie
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    needs:
#      - publish
#    if: github.ref == 'refs/heads/main'
#    steps:
#    - name: Deploy
#      uses: appleboy/ssh-action@v0.1.10
#      with:
#        host: ${{ secrets.DEPLOY_HOST }}
#        username: ${{ secrets.DEPLOY_USER }}
#        key: ${{ secrets.DEPLOY_KEY }}
